## data encoding

## nominal/One Hot Encoding

In [1]:
import pandas as pd 

In [2]:
from sklearn.preprocessing import OneHotEncoder

In [3]:
sy=pd.DataFrame({
      'color':['blue','green','black','red','orange','blue']})

In [4]:
encoder=OneHotEncoder()

In [5]:
encoder.fit_transform(sy[['color']])

<6x5 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [6]:
encoded=encoder.fit_transform(sy[['color']]).toarray()

In [7]:
encoder_sy=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [8]:
encoder_sy

color_black  color_blue  color_green  color_orange  color_red
0          0.0         1.0          0.0           0.0        0.0
1          0.0         0.0          1.0           0.0        0.0
2          1.0         0.0          0.0           0.0        0.0
3          0.0         0.0          0.0           0.0        1.0
4          0.0         0.0          0.0           1.0        0.0
5          0.0         1.0          0.0           0.0        0.0

In [9]:
encoder.transform([['blue']]).toarray()

/config/.local/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 1., 0., 0., 0.]])

In [10]:
pd.concat([sy,encoder_sy],axis=1)

color  color_black  color_blue  color_green  color_orange  color_red
0    blue          0.0         1.0          0.0           0.0        0.0
1   green          0.0         0.0          1.0           0.0        0.0
2   black          1.0         0.0          0.0           0.0        0.0
3     red          0.0         0.0          0.0           0.0        1.0
4  orange          0.0         0.0          0.0           1.0        0.0
5    blue          0.0         1.0          0.0           0.0        0.0

In [11]:
encoded

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.]])

## label encoding

In [12]:
sy.head()

color
0    blue
1   green
2   black
3     red
4  orange

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
lbl_enc=LabelEncoder()

In [15]:
lbl_enc.fit_transform(sy[['color']])

/config/.local/lib/python3.8/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 2, 0, 4, 3, 1])

In [16]:
lbl_enc.transform([['blue']])

/config/.local/lib/python3.8/site-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([1])

In [17]:
lbl_enc.transform([['green']])

/config/.local/lib/python3.8/site-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

## ordinal encoding

In [18]:
from sklearn.preprocessing import OrdinalEncoder

In [19]:
sd=pd.DataFrame({
    'size':['small','large','medium','large','small','medium']
})

In [20]:
sd

size
0   small
1   large
2  medium
3   large
4   small
5  medium

In [21]:
ord_enc=OrdinalEncoder()

In [22]:
ord_enc.fit_transform(sd[['size']])

array([[2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [1.]])

In [23]:
ord_enc=OrdinalEncoder(categories=[['small','medium','large']])

In [24]:
ord_enc.fit_transform(sd[['size']])

array([[0.],
       [2.],
       [1.],
       [2.],
       [0.],
       [1.]])

## target guided ordinal encoding

In [25]:
stg=pd.DataFrame({
    'city':['tokyo','new york','london','mumbai','tokyo','paris','mumbai','new york'],
    'price':[260,200,220,140,285,190,165,230]
})

In [26]:
stg

city  price
0     tokyo    260
1  new york    200
2    london    220
3    mumbai    140
4     tokyo    285
5     paris    190
6    mumbai    165
7  new york    230

In [27]:
mean_price=stg.groupby('city')['price'].mean().to_dict()

In [28]:
mean_price

{'london': 220.0,
 'mumbai': 152.5,
 'new york': 215.0,
 'paris': 190.0,
 'tokyo': 272.5}

In [29]:
stg['city_encoded']=stg['city'].map(mean_price)

In [30]:
stg

city  price  city_encoded
0     tokyo    260         272.5
1  new york    200         215.0
2    london    220         220.0
3    mumbai    140         152.5
4     tokyo    285         272.5
5     paris    190         190.0
6    mumbai    165         152.5
7  new york    230         215.0

In [31]:
stg[['price','city_encoded']]

price  city_encoded
0    260         272.5
1    200         215.0
2    220         220.0
3    140         152.5
4    285         272.5
5    190         190.0
6    165         152.5
7    230         215.0

In [32]:
##assignment 
import seaborn as sb

In [33]:
dnd=sb.load_dataset('tips')

In [34]:
dnd

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [35]:
mean_bill=dnd.groupby('time')['total_bill'].mean().to_dict()

In [36]:
mean_bill

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [37]:
dnd['time_encoded']=dnd['time'].map(mean_bill)

In [38]:
dnd

total_bill   tip     sex smoker   day    time  size time_encoded
0         16.99  1.01  Female     No   Sun  Dinner     2    20.797159
1         10.34  1.66    Male     No   Sun  Dinner     3    20.797159
2         21.01  3.50    Male     No   Sun  Dinner     3    20.797159
3         23.68  3.31    Male     No   Sun  Dinner     2    20.797159
4         24.59  3.61  Female     No   Sun  Dinner     4    20.797159
..          ...   ...     ...    ...   ...     ...   ...          ...
239       29.03  5.92    Male     No   Sat  Dinner     3    20.797159
240       27.18  2.00  Female    Yes   Sat  Dinner     2    20.797159
241       22.67  2.00    Male    Yes   Sat  Dinner     2    20.797159
242       17.82  1.75    Male     No   Sat  Dinner     2    20.797159
243       18.78  3.00  Female     No  Thur  Dinner     2    20.797159

[244 rows x 8 columns]

In [39]:
dnd[['time_encoded','total_bill']]

time_encoded  total_bill
0      20.797159       16.99
1      20.797159       10.34
2      20.797159       21.01
3      20.797159       23.68
4      20.797159       24.59
..           ...         ...
239    20.797159       29.03
240    20.797159       27.18
241    20.797159       22.67
242    20.797159       17.82
243    20.797159       18.78

[244 rows x 2 columns]