## logistic regression 

In [1]:
from sklearn.datasets import load_iris
import warnings
warnings.filterwarnings('ignore')

In [2]:
dataset=load_iris()

In [3]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [4]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [5]:
import pandas as pd
import numpy as np

In [6]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [7]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
df['target']=dataset.target

In [9]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [10]:
df['target'].unique()

array([0, 1, 2])

In [11]:
df[df['target']!=2]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
95       1  
96       1  
97       1  
98       1  
99       1  

[100 rows x 5 columns]

In [12]:
df_c=df[df['target']!=2]

In [13]:
df_c['target'].unique()

array([0, 1])

In [14]:
x=df_c.iloc[:,:-1]
y=df_c.iloc[:,-1]

In [15]:
from sklearn.model_selection import train_test_split
x_test,x_train,y_test,y_train=train_test_split(x,y,test_size=0.20,random_state=42)

In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
classification=LogisticRegression(max_iter=200)

In [18]:
classification.fit(x_train,y_train)

LogisticRegression(max_iter=200)

In [19]:
y_pred=classification.predict(x_test)

In [20]:
y_pred

array([1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1])

## confusion matrix, accuracy and classification report

In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [22]:
print(confusion_matrix(y_test,y_pred))

[[38  0]
 [ 0 42]]


In [23]:
print(accuracy_score(y_test,y_pred))

1.0


In [24]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        38
           1       1.00      1.00      1.00        42

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80



In [25]:
from sklearn.model_selection import KFold

In [26]:
cv=KFold(n_splits=5,shuffle=True)

In [27]:
cv

KFold(n_splits=5, random_state=None, shuffle=True)

In [28]:
from sklearn.model_selection import cross_val_score

In [29]:
scores=cross_val_score(classification,x_train,y_train,scoring='accuracy',cv=cv)

In [30]:
scores

array([1., 1., 1., 1., 1.])

In [31]:
np.mean(scores)

1.0

In [32]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
x,y=make_classification(n_samples=1000,n_features=10,n_informative=5,n_redundant=5,n_classes=2,random_state=1)

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
x_test,x_train,y_test,y_train=train_test_split(x,y,test_size=0.20,random_state=42)

In [35]:
complex_class=LogisticRegression(max_iter=200)

In [36]:
complex_class.fit(x_train,y_train)

LogisticRegression(max_iter=200)

In [37]:
y_pred_complex=complex_class.predict(x_test)

In [38]:
print(confusion_matrix(y_test,y_pred_complex))

[[332  76]
 [ 81 311]]


In [39]:
print(accuracy_score(y_test,y_pred_complex))

0.80375


In [40]:
print(classification_report(y_test,y_pred_complex))

              precision    recall  f1-score   support

           0       0.80      0.81      0.81       408
           1       0.80      0.79      0.80       392

    accuracy                           0.80       800
   macro avg       0.80      0.80      0.80       800
weighted avg       0.80      0.80      0.80       800



In [41]:
cv=KFold(n_splits=5)
cross_val_score(complex_class,x_train,y_train,cv=cv)

array([0.7  , 0.825, 0.85 , 0.775, 0.875])

In [42]:
np.mean(cross_val_score(complex_class,x_train,y_train,cv=cv))

0.805

## logistic regression hyperparameter tuning

In [43]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
x,y=make_classification(n_samples=1000,n_features=10,n_informative=5,n_redundant=5,n_classes=2,random_state=1)

In [44]:
from sklearn.model_selection import train_test_split
x_test,x_train,y_test,y_train=train_test_split(x,y,test_size=0.20,random_state=42)

## model training hyperparameter tuning
### gridsearchcv

In [45]:
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [46]:
parameters={'penalty':('l1','l2','elasticnet'),'C':[1,5,15,25,35]}


In [47]:
classifier=LogisticRegression()

In [48]:
clff=GridSearchCV(classifier,param_grid=parameters,cv=5)

In [49]:
## splittig of training data into train and validation
clff.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 5, 15, 25, 35],
                         'penalty': ('l1', 'l2', 'elasticnet')})

In [50]:
clff.best_params_

{'C': 1, 'penalty': 'l2'}

In [51]:
clff.best_score_

0.805

In [52]:
classifier=LogisticRegression(C=1,penalty='l2')

In [53]:
classifier.fit(x_train,y_train)

LogisticRegression(C=1)

In [54]:
y_pred=classifier.predict(x_test)

In [55]:
y_pred_prob=classifier.predict_proba(x_test)

In [56]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [57]:
print(confusion_matrix(y_test,y_pred))


[[332  76]
 [ 81 311]]


In [58]:
print(accuracy_score(y_test,y_pred))


0.80375


In [59]:
print(classification_report(y_test,y_pred))


              precision    recall  f1-score   support

           0       0.80      0.81      0.81       408
           1       0.80      0.79      0.80       392

    accuracy                           0.80       800
   macro avg       0.80      0.80      0.80       800
weighted avg       0.80      0.80      0.80       800



## randomizedsearchcv

In [60]:
from sklearn.model_selection import RandomizedSearchCV

In [61]:
random_clff=RandomizedSearchCV(LogisticRegression(),param_distributions=parameters,cv=5,n_iter=20)
    

In [62]:
random_clff.fit(x_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=20,
                   param_distributions={'C': [1, 5, 15, 25, 35],
                                        'penalty': ('l1', 'l2', 'elasticnet')})

In [63]:
random_clff.best_params_

{'penalty': 'l2', 'C': 1}

In [64]:
random_classifier=LogisticRegression(penalty='l2',C=1)

In [65]:
random_classifier.fit(x_train,y_train)

LogisticRegression(C=1)

In [66]:
y_pred=random_classifier.predict(x_test)

In [67]:
print(accuracy_score(y_test,y_pred))


0.80375


In [68]:
print(confusion_matrix(y_test,y_pred))


[[332  76]
 [ 81 311]]


In [69]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.80      0.81      0.81       408
           1       0.80      0.79      0.80       392

    accuracy                           0.80       800
   macro avg       0.80      0.80      0.80       800
weighted avg       0.80      0.80      0.80       800



## multiclass classifiction

In [70]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
x,y=make_classification(n_samples=1000,n_features=10,n_informative=5,n_redundant=5,n_classes=3,random_state=1)

In [71]:
model=LogisticRegression(multi_class='ovr',solver='lbfgs')

In [72]:
from sklearn.model_selection import train_test_split

In [73]:
x_test,x_train,y_test,y_train=train_test_split(x,y,test_size=0.20,random_state=42)

In [74]:
model.fit(x_train,y_train)

LogisticRegression(multi_class='ovr')

In [75]:
y_pred=model.predict(x_test)

In [76]:
y_pred_prob=model.predict_proba(x_test)

In [77]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [78]:
print(confusion_matrix(y_test,y_pred))

[[211  37   9]
 [ 42 175  53]
 [ 62  32 179]]


In [79]:
print(accuracy_score(y_test,y_pred))

0.70625


In [80]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.67      0.82      0.74       257
           1       0.72      0.65      0.68       270
           2       0.74      0.66      0.70       273

    accuracy                           0.71       800
   macro avg       0.71      0.71      0.71       800
weighted avg       0.71      0.71      0.70       800

